[package]
name = "game_module"
edition.workspace = true
version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
block-client = { path = "../../block-client" }
block-editor-plugin = { path = "../../block-editor-plugin" }
game-host = { path = "../../tabletop_games/host" }
uuid = "1"

[dev-dependencies]
block-ui-test = { path = "../../block-ui-test" }

[lints]
workspace = true
