[package]
name = "counter"
edition.workspace = true
version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "counter-host"
path = "src/main.rs"

[dependencies]
block-client = { path = "../../block-client" }
block-editor-plugin = { path = "../../block-editor-plugin", default-features = false }
uuid = "1"

[features]
default = ["native"]
native = ["block-editor-plugin/native"]
hosted = ["block-editor-plugin/hosted"]

[dev-dependencies]
block-ui-test = { path = "../../block-ui-test" }

[lints]
workspace = true
