use super::*;

mod web_browser_tab_history_changes_current_index;
mod web_browser_tab_new_starts_at_about_blank;
mod web_browser_tab_push_appends_and_selects_url;
mod web_browser_tab_push_discards_forward_history;
mod web_browser_tab_replace_changes_current_url;
mod web_browser_tab_title_determines_implicit_name;
