use std::cell::{Cell, RefCell};
use std::panic::{catch_unwind, AssertUnwindSafe};
use std::rc::Rc;

use crate::{
    batch, create_effect, create_memo, create_selector, create_signal, on_cleanup, owner_scope,
    untrack, Scope,
};

mod a_context_reaches_the_effects_a_nested_scope_creates;
mod a_panicking_effect_can_run_again;
mod a_scope_opened_inside_an_effect_belongs_to_the_effects_owner;
mod a_selector_forgets_keys_whose_watchers_were_disposed;
mod a_selector_memo_tracks_one_key_without_watching_the_source;
mod a_selector_only_reruns_the_keys_that_gained_or_lost_selection;
mod all_cleanups_run_even_when_one_panics;
mod cleanup_precedes_next_execution;
mod cleanup_reads_do_not_become_dependencies;
mod conditional_dependencies_are_replaced;
mod conditional_memos_replace_dependencies;
mod diamond_and_direct_dependencies_never_glitch;
mod disposal_releases_captured_resources;
mod disposed_memos_cannot_return_stale_values;
mod downstream_effect_recovers_after_memo_panics;
mod dropping_scope_cancels_queued_effects;
mod effects_can_write_signals_and_settle_without_recursion;
mod memo_panic_can_be_retried;
mod memo_writes_are_rejected_even_when_untracked;
mod memos_are_lazy_cached_and_filter_equal_outputs;
mod nested_batches_defer_effects_but_memo_reads_are_current;
mod nested_effects_are_disposed_before_parent_reruns;
mod non_clone_values_can_be_read_and_updated;
mod panic_restores_tracking_and_batching;
mod panicking_update_still_invalidates_mutated_value;
mod repeated_reads_only_subscribe_once;
mod runaway_effects_are_stopped_and_scheduler_remains_usable;
mod scopes_dispose_effects_and_run_cleanup_once;
mod selector_reads_are_current_inside_a_batch;
mod signals_track_changes_and_skip_equal_sets;
mod the_nearest_context_shadows_the_ones_above_it;
mod untracked_memo_reads_still_refresh_without_subscribing;
mod untracked_reads_do_not_subscribe;
