[workspace]
members = [
    "crates/beui",
    "crates/tablet",
    "crates/reactive",
    "crates/block",
    "crates/block-server",
    "crates/block-client",
    "crates/block-ui",
    "crates/block-ui-test",
    "crates/text-editor-core",
    "crates/block-e2e",
    "crates/block-app",
    "crates/tabletop_games/api",
    "crates/tabletop_games/host",
    "crates/tabletop_games/rules/connect_four",
    "crates/tabletop_games/rules/crazy_8s",
    "crates/tabletop_games/rules/tic_tac_toe",
    "crates/citygame",
    "crates/citygenerator",
    "crates/logicgame",
    "crates/cvl2",
    "crates/editors/audio_block",
    "crates/editors/calendar",
    "crates/editors/checklist",
    "crates/editors/compiled_logic",
    "crates/editors/counter",
    "crates/editors/database",
    "crates/editors/database_schema",
    "crates/editors/database_view",
    "crates/editors/gui_builder",
    "crates/editors/hotbar",
    "crates/editors/image_block",
    "crates/editors/logic_game",
    "crates/editors/map",
    "crates/editors/paint_review",
    "crates/editors/pdf",
    "crates/editors/pixel_art",
    "crates/editors/pixel_ray_tracer",
    "crates/editors/presentation",
    "crates/editors/settings",
    "crates/editors/ui_settings",
    "crates/editors/version_control_data",
    "crates/editors/version_control_worktree",
    "crates/editors/video_block",
    "crates/editors/workspace_index",
    "crates/block-editor-plugin",
    "crates/block-gpu-abi",
    "crates/block-gpu-guest",
    "crates/block-gpu-host",
    "crates/block-gpu-shim",
    "crates/block-wasm-host",
    "crates/block-plugin-api",
    "crates/gpui-demo",
    "crates/paint-snapshot",
    "crates/fix-rust-source",
    "crates/wasi-threads",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT"

[workspace.lints.clippy]
too_many_arguments = "allow"

[profile.release-check]
inherits = "dev"
debug-assertions = false
overflow-checks = false
debug = false
incremental = false

[profile.plugin]
inherits = "dev"
opt-level = 2
debug = false
strip = "debuginfo"
incremental = false

[profile.plugin-release]
inherits = "release"
strip = "debuginfo"
