[workspace]
members = [
    "crates/tablet",
    "crates/reactive",
    "crates/block",
    "crates/block-server",
    "crates/block-client",
    "crates/block-e2e",
    "crates/block-app",
    "crates/citygame",
    "crates/citygenerator",
    "crates/logicgame",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT"
