use super::*;

mod text_history_restores_bytes_after_later_ids_change;
mod text_history_undoes_and_redoes_grouped_edits;
mod text_implicit_name_stops_at_newline_and_a_utf8_boundary;
mod text_indent_width_round_trips_through_operations_and_serialization;
mod text_item_ids_resolve_visible_characters;
mod text_language_round_trips_through_operations_and_serialization;
mod text_operations_are_crdt_updates_and_do_not_keep_a_confirmed_copy;
mod text_remove_item_operation_targets_stable_id;
mod text_serialization_preserves_invalid_utf8_bytes;
mod text_tracks_embedded_block_references;
