[package]
name = "connect_four"
edition.workspace = true
version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
game-api = { path = "../../game-api" }
uuid = { version = "1", default-features = false }

[build-dependencies]
game-api = { path = "../../game-api" }

[dev-dependencies]
bincode = "1"
deterministic_games = { path = "../../deterministic_games" }
uuid = { version = "1", features = ["v4"] }

[lints]
workspace = true
