[package]
name = "paint-snapshot"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
bincode = "1"
egui = "0.34.3"
flate2 = "1"
image = { version = "0.25", default-features = false, features = ["png"] }
serde = { version = "1", features = ["derive"] }

[lints]
workspace = true
