[package]
name = "block-client"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
base64 = "0.22"
block = { path = "../block" }
eips = { version = "0.2.4", features = ["serde"] }
futures-util = "0.3"
parking_lot = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
tokio-tungstenite = "0.23"
uuid = { version = "1", features = ["serde", "v4"] }
