[package]
name = "crazy_8s"
edition.workspace = true
version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
game-api = { path = "../../api" }

[build-dependencies]
game-api = { path = "../../api" }

[dev-dependencies]
game-host = { path = "../../host" }
uuid = { version = "1", features = ["v4"] }

[lints]
workspace = true
