[package]
name = "logic_game"
edition.workspace = true
version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
block = { path = "../../block" }
block-client = { path = "../../block-client" }
block-editor-plugin = { path = "../../block-editor-plugin" }
logicgame = { path = "../../logicgame" }
uuid = "1"

[dev-dependencies]
block-ui-test = { path = "../../block-ui-test" }

[lints]
workspace = true
