[package]
name = "beui"
edition.workspace = true
version.workspace = true
license.workspace = true

[features]
default = ["window"]
render = ["dep:bytemuck", "dep:wgpu", "wgpu/std", "wgpu/wgsl"]
window = ["render", "dep:arboard", "dep:pollster", "dep:winit", "wgpu/default"]

[dependencies]
beui_macros = { path = "../beui_macros" }
bon = "3"
bytemuck = { version = "1", features = ["derive"], optional = true }
freetype = "0.7"
harfbuzz_rs = "2"
pollster = { version = "0.4", optional = true }
reactive = { path = "../reactive" }
text-editor-core = { path = "../text-editor-core" }
unicode-script = "0.5"
wgpu = { version = "29", default-features = false, optional = true }
winit = { version = "0.30", optional = true }

[target.'cfg(not(any(target_os = "android", target_os = "ios", target_arch = "wasm32")))'.dependencies]
arboard = { version = "3.6", default-features = false, optional = true }

[lints]
workspace = true

[[example]]
name = "demo"
required-features = ["window"]

[[example]]
name = "counter"
required-features = ["window"]
