[package]
name = "block-app"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
block = { path = "../block" }
block-client = { path = "../block-client" }
block-server = { path = "../block-server" }
eframe = { version = "0.34.3", default-features = false, features = ["default_fonts", "persistence", "wgpu", "wayland", "x11"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["net", "rt-multi-thread"] }
uuid = { version = "1", features = ["serde", "v4"] }
wry = "0.55.1"
