[package]
name = "block-app"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
arboard = "3.6"
block = { path = "../block" }
block-client = { path = "../block-client" }
block-server = { path = "../block-server" }
eframe = { version = "0.34.3", default-features = false, features = ["default_fonts", "persistence", "wgpu", "wayland", "x11"] }
image = { version = "0.25", default-features = false, features = ["bmp", "gif", "ico", "jpeg", "png", "pnm", "tga", "tiff", "webp"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["net", "rt-multi-thread"] }
uuid = { version = "1", features = ["serde", "v4"] }
wry = "0.55.1"
