[package]
name = "file_tree"
edition.workspace = true
version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
block = { path = "../../block" }
block-client = { path = "../../block-client" }
block-editor-plugin = { path = "../../block-editor-plugin" }
uuid = "1"

[lints]
workspace = true
