[package]
name = "logic_grid"
edition.workspace = true
version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
block = { path = "../../block" }
block-client = { path = "../../block-client" }
block-editor-plugin = { path = "../../block-editor-plugin" }
bytemuck = { version = "1", features = ["derive"] }
logicgame = { path = "../../logicgame" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
block-ui-test = { path = "../../block-ui-test" }

[lints]
workspace = true
